# Generated by Django 5.1.1 on 2024-09-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
