# Generated by Django 5.1.1 on 2024-09-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_language_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='bio_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='code_en',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='code_ru',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
